# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, unique=True)),
            ],
            options={
                'db_table': 'body',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarModelOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, unique=True)),
                ('generation_count', models.CharField(blank=True, max_length=253)),
                ('url', models.CharField(max_length=253)),
                ('bottom_age', models.IntegerField(blank=True, null=True)),
                ('top_age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngineOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, unique=True)),
            ],
            options={
                'db_table': 'engine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253)),
                ('cost', models.IntegerField()),
            ],
            options={
                'db_table': 'equipment_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentLk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'equipment_lk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'db_table': 'feature_dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureLk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'feature_lk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GearDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, unique=True)),
            ],
            options={
                'db_table': 'gear',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenerationOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253)),
                ('cost', models.CharField(max_length=253)),
                ('url', models.CharField(max_length=253, unique=True)),
                ('generation', models.CharField(blank=True, max_length=253)),
                ('bottom_age', models.IntegerField()),
                ('top_age', models.IntegerField()),
            ],
            options={
                'db_table': 'generation',
                'ordering': ['-bottom_age'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, unique=True)),
                ('group_name', models.CharField(max_length=253)),
                ('url', models.CharField(max_length=253)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'mark',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModificationOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253)),
                ('url', models.CharField(max_length=253, unique=True)),
                ('complects_url', models.CharField(blank=True, max_length=253)),
                ('cost', models.CharField(blank=True, max_length=253, null=True)),
                ('equipment_name', models.CharField(blank=True, max_length=253)),
            ],
            options={
                'db_table': 'modification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=127)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=127)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.CarMake')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.CarMake')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.CarModel')),
            ],
            options={
                'ordering': ['-year_start'],
            },
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('old_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.Body')),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.CarMake')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.CarModel')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.Engine')),
                ('equipment', models.ManyToManyField(through='kreddb.EquipmentCost', to='kreddb.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='ModificationFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=127)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.Feature')),
                ('modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.Modification')),
            ],
        ),
        migrations.AddField(
            model_name='modification',
            name='features',
            field=models.ManyToManyField(through='kreddb.ModificationFeatures', to='kreddb.Feature'),
        ),
        migrations.AddField(
            model_name='modification',
            name='gear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.Gear'),
        ),
        migrations.AddField(
            model_name='modification',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.Generation'),
        ),
        migrations.AddField(
            model_name='equipmentcost',
            name='modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.Modification'),
        ),
        migrations.CreateModel(
            name='GearOld',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('kreddb.geardb',),
        ),
        migrations.AlterUniqueTogether(
            name='modificationfeatures',
            unique_together=set([('modification', 'feature')]),
        ),
        migrations.AlterUniqueTogether(
            name='generation',
            unique_together=set([('name', 'car_model', 'year_start', 'year_end')]),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentcost',
            unique_together=set([('modification', 'equipment')]),
        ),
    ]
