# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GearOld',
        ),
    ]
