# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0002_delete_gearold'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='group',
            field=models.CharField(choices=[('SF', 'Безопасность'), ('CF', 'Комфорт'), ('VW', 'Обзор'), ('IN', 'Салон'), ('MM', 'Мультимедиа'), ('CJ', 'Защита от угона'), ('EX', 'Экстерьер'), ('--', 'Not set')], default='--', max_length=2),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rank',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='group',
            field=models.CharField(choices=[('GE', 'Общая информация'), ('SF', 'Безопасность'), ('EX', 'Эксплуатационные показатели'), ('EN', 'Двигатель'), ('GR', 'Трансмиссия'), ('SZ', 'Размеры в мм'), ('VM', 'Объем и масса'), ('SB', 'Подвеска и тормоза'), ('--', 'Not set')], default='--', max_length=2),
        ),
        migrations.AddField(
            model_name='feature',
            name='rank',
            field=models.SmallIntegerField(null=True),
        ),
    ]
