# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0004_auto_20160606_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmake',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='group',
            field=models.CharField(choices=[('GE', 'Общая информация'), ('SR', 'Безопасность'), ('EC', 'Эксплуатационные показатели'), ('EN', 'Двигатель'), ('GR', 'Трансмиссия'), ('SZ', 'Размеры в мм'), ('VM', 'Объем и масса'), ('SB', 'Подвеска и тормоза')], max_length=2),
        ),
    ]
