# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0005_auto_20160624_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.Generation')),
            ],
        ),
    ]
