# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0006_generationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='year_end',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
