# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import kreddb.models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0007_auto_20160715_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationimage',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generationimage',
            name='image',
            field=models.ImageField(upload_to=kreddb.models.car_image_path),
        ),
    ]
