# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import kreddb.models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0009_auto_20160728_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=kreddb.models.car_image_path)),
                ('main', models.BooleanField(default=False)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.Body')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.Generation')),
            ],
        ),
        migrations.RemoveField(
            model_name='generationimage',
            name='generation',
        ),
        migrations.DeleteModel(
            name='GenerationImage',
        ),
    ]
