# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0011_auto_20160818_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
