# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0012_generation_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(db_index=True, max_length=127)),
                ('json_value', models.TextField()),
            ],
        ),
    ]
