# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0013_siteoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteoptions',
            name='option',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
