# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0014_auto_20160821_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.Body')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.Generation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='carinfo',
            unique_together=set([('generation', 'body')]),
        ),
    ]
