# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0015_auto_20160515_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='equipment'
        )
    ]
