# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0016_auto_20160917_2330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarModelNew',
            new_name='CarModel',
        ),
    ]
