# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0016_auto_20160515_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=127)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModelNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=127)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.CarMake')),
            ],
        ),
        migrations.CreateModel(
            name='EngineNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GearNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenerationNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.CarMake')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.CarModelNew')),
            ],
            options={
                'ordering': ['-year_start'],
            },
        ),
        migrations.CreateModel(
            name='ModificationFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=127)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.Features')),
            ],
        ),
        migrations.CreateModel(
            name='ModificationNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.BodyNew')),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.CarMake')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.CarModelNew')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.EngineNew')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.GearNew')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.GenerationNew')),
            ],
        ),
        migrations.AddField(
            model_name='modificationfeatures',
            name='modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.ModificationNew'),
        ),
        migrations.AddField(
            model_name='equipmentcost',
            name='modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.ModificationNew'),
        ),
        migrations.AlterUniqueTogether(
            name='modificationfeatures',
            unique_together=set([('modification', 'feature')]),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentcost',
            unique_together=set([('modification', 'equipment')]),
        ),
    ]
