# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0017_auto_20160917_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='body_override',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='generation_override',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='model_family',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kreddb.ModelFamily'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='name_override',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together=set([('model_family', 'generation', 'body', 'name_override', 'generation_override', 'body_override')]),
        ),
    ]
