# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0018_auto_20160515_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationnew',
            name='name',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
