# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0018_auto_20160917_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kreddb.CarModel'),
        ),
    ]
