# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0019_auto_20160515_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodynew',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='carmake',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='carmodelnew',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='enginenew',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='gearnew',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='modificationnew',
            name='old_id',
        ),
        migrations.AlterField(
            model_name='generationnew',
            name='name',
            field=models.CharField(blank=True, default='', max_length=127),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modificationnew',
            name='name',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.RemoveField(
            model_name='generationnew',
            name='old_id',
        ),
        migrations.AlterUniqueTogether(
            name='generationnew',
            unique_together=set([('name', 'car_model', 'year_start', 'year_end')]),
        ),
    ]
