# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 09:13
from __future__ import unicode_literals

from django.db import migrations


def create_car_models(apps, schema_editor):
    Modification = apps.get_model("kreddb", "Modification")
    CarModel = apps.get_model("kreddb", "CarModel")
    CarImage = apps.get_model("kreddb", "CarImage")
    for modification in Modification.objects.all():
        car_model, created = CarModel.objects.get_or_create(
            model_family=modification.model_family,
            generation=modification.generation,
            body=modification.body
        )
        modification.car_model = car_model
        modification.save()
        if created:
            for car_image in CarImage.objects.filter(
                    generation=modification.generation,
                    body=modification.body
            ):
                car_image.car_model = car_model
                car_image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0019_modification_car_model'),
    ]

    operations = [
        migrations.RunPython(create_car_models),
    ]
