# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0020_auto_20160515_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='features',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
