# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0022_auto_20160918_1506'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together=set([('model_family', 'generation', 'body', 'name_override', 'body_override')]),
        ),
    ]
