# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0021_auto_20160515_2250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
        migrations.AddField(
            model_name='modificationnew',
            name='equipment',
            field=models.ManyToManyField(through='kreddb.EquipmentCost', to='kreddb.Equipment'),
        ),
        migrations.AddField(
            model_name='modificationnew',
            name='features',
            field=models.ManyToManyField(through='kreddb.ModificationFeatures', to='kreddb.Feature'),
        ),
    ]
