# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0022__alter_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='alias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelfamily',
            name='alias',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='body_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_overriden', to='kreddb.Body'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_family_overriden', to='kreddb.ModelFamily'),
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='do_body_override',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='do_generation_override',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='do_name_override',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='generation_override',
        ),
    ]
