# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0022_auto_20160515_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificationnew',
            name='old_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
