# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0023_modificationnew_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(db_index=True, max_length=511),
        ),
    ]
