# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0025_auto_20160518_2354'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='bodycustom',
        #     name='body_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='carmodelcustom',
        #     name='carmodel_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='carmodelcustom',
        #     name='model_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='markcustom',
        #     name='mark_ptr',
        # ),
        migrations.DeleteModel(
            name='BodyCustom',
        ),
        migrations.DeleteModel(
            name='CarModelCustom',
        ),
        migrations.DeleteModel(
            name='MarkCustom',
        ),
    ]
