# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0026__alter_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='body_override',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='name_override',
        ),
    ]
