# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0026_auto_20160522_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'body',
            },
        ),
        migrations.CreateModel(
            name='CarModelOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, unique=True)),
                ('generation_count', models.CharField(blank=True, max_length=253)),
                ('url', models.CharField(max_length=253)),
                ('bottom_age', models.IntegerField(blank=True, null=True)),
                ('top_age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'model',
            },
        ),
        migrations.CreateModel(
            name='EngineOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'engine',
            },
        ),
        migrations.RenameModel(
            old_name='BodyNew',
            new_name='BodyA',
        ),
        migrations.RenameModel(
            old_name='CarModelNew',
            new_name='CarModelA',
        ),
        migrations.RenameModel(
            old_name='EngineNew',
            new_name='EngineA',
        ),
        migrations.RenameModel(
            old_name='GearNew',
            new_name='GearA',
        ),
        migrations.RenameModel(
            old_name='GenerationNew',
            new_name='GenerationA',
        ),
        migrations.RenameModel(
            old_name='Generation',
            new_name='GenerationOld',
        ),
        migrations.RenameModel(
            old_name='ModificationNew',
            new_name='ModificationA',
        ),
        migrations.DeleteModel(
            name='Gear',
        ),
        migrations.CreateModel(
            name='GearOld',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('kreddb.geardb',),
        ),
        # migrations.RemoveField(
        #     model_name='enginecustom',
        #     name='engine_ptr',
        # ),
        migrations.AlterField(
            model_name='generationold',
            name='car_model',
            field=models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, to='kreddb.CarModelOld'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.BodyOld'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='car_model',
            field=models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, to='kreddb.CarModelOld'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.EngineOld'),
        ),
        # migrations.AddField(
        #     model_name='enginecustom',
        #     name='engineold_ptr',
        #     field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kreddb.EngineOld'),
        #     preserve_default=False,
        # ),
    ]
