# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0026_auto_20160927_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='body',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='modelfamily',
            name='alias',
        ),
    ]
