# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 21:24
from __future__ import unicode_literals

from django.db import migrations


def copy_car_model_name(apps, schema_editor):
    CarModel = apps.get_model("kreddb", "CarModel")
    for car_model in CarModel.objects.all():
        car_model.name = car_model.model_family.name
        car_model.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0027_auto_20160927_0023'),
    ]

    operations = [
        migrations.RunPython(copy_car_model_name),
    ]
