# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0027_auto_20160522_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enginecustom',
            name='engine_ptr',
        ),
        migrations.DeleteModel(
            name='EngineCustom',
        ),
    ]
