# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0028_auto_20160927_0024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together=set([('name', 'generation', 'body')]),
        ),
    ]
