# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0029_auto_20160928_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='model_family',
        ),
    ]
