# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0029_auto_20160522_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modification',
            new_name='ModificationOld',
        ),
    ]
