# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0030_remove_carmodel_model_family'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carinfo',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='body',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='generation',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price_per_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CarInfo',
        ),
    ]
