# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0031_auto_20161002_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='model_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kreddb.ModelFamily'),
        ),
    ]
