# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 21:09
from __future__ import unicode_literals

from django.db import migrations


def set_model_family(apps, schema_editor):
    CarModel = apps.get_model("kreddb", "CarModel")
    for car_model in CarModel.objects.all():
        car_model.model_family = car_model.generation.model_family
        car_model.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0032_carmodel_model_family'),
    ]

    operations = [
        migrations.RunPython(set_model_family)
    ]
