# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0034_auto_20161005_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.CarModel'),
        ),
    ]
