# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0035_auto_20161009_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmake',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
