# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0036_auto_20161030_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('description_pos', models.CharField(choices=[('T', 'Наверху'), ('B', 'Внизу')], max_length=1)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreddb.CarModel')),
            ],
        ),
    ]
