# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0037_cardescription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardescription',
            unique_together=set([('car_model', 'description_pos')]),
        ),
    ]
