# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0038_auto_20170509_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='related',
            field=models.ManyToManyField(related_name='_carmodel_related_+', to='kreddb.CarModel'),
        ),
    ]
