# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreddb', '0039_carmodel_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_carmodel_related_+', to='kreddb.CarModel'),
        ),
    ]
